version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: install system dependencies
          command: |
            sudo apt-get install -yq libdbus-1-dev
      - restore_cache:
          keys:
            - cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}-v1
      - run: make dev
      - run: make test
      - save_cache:
          paths:
            - "/usr/local/cargo/registry"
            - "target"
          key: cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}-v1
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
